package ai.fin.enums;

/**
 * Role of a message within a chat conversation.
 */
public enum MessageRole {

    /**
     * Message sent by the user.
     */
    USER,

    /**
     * Message generated by the AI assistant.
     */
    ASSISTANT
}